[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.4"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
